import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Inter } from "next/font/google";

import Footer from "@/component/layout/Footer";
import Header from "@/component/layout/Header";
import LeftAside from "@/component/layout/LeftAside";
import RightAside from "@/component/layout/RightAside";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container p-0">
          <Header />
          <main className="py-4 px-3">
            <div className="row">
              <LeftAside />
              {children}
              <RightAside />
            </div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
